//! Shim source code generation.
//!
//! This module generates Rust source code for shim layers from a
//! [`calxgloss_types::ShimLayer`] mapping table. Each shim layer bridges
//! a Windows DLL's exported API surface to a target Rust crate's API.
//!
//! # Flow
//!
//! 1. After [`super::shim::generate_shim_mappings`] produces a [`ShimLayer`],
//!    call [`generate_shim_source`] to produce the Rust source code.
//! 2. The generated code is written to `re/shims/<dll_name>/shim.rs`.
//! 3. Downstream steps (test generation, verification) consume the source file.
//!
//! # Generated Code Structure
//!
//! The output is a complete Rust module containing:
//! - A module-level state struct (if mappings require shared resources)
//! - One exported `unsafe` function per mapping, routing to the target crate
//! - Inline comments documenting each mapping's parameter transforms
//! - `TODO` placeholders for mappings requiring non-trivial return conversion

use calxgloss_types::{ComplexityScore, ReturnMapping, ShimApiMapping, ShimLayer};

/// Configuration controlling how aggressively the generator fills in
/// stubs versus leaving `TODO` markers for manual review.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ShimGenerationMode {
    /// Generate complete, compilable code where possible. Leave `TODO` only
    /// for mappings that require significant manual work (e.g. complex type
    /// conversions or multi-step API sequences).
    Complete,

    /// Generate skeletal stubs for all mappings, with clear `TODO` comments
    /// explaining what each function needs to implement. Useful for getting
    /// the overall structure right before filling in details.
    Skeletal,
}

impl Default for ShimGenerationMode {
    fn default() -> Self {
        Self::Complete
    }
}

/// Generates Rust source code for a shim layer.
///
/// Given a [`ShimLayer`] with its API mappings, produces a complete Rust
/// source file as a string. The generated code implements every exported
/// function from the original DLL, routing calls to the equivalent target
/// crate API.
///
/// # Arguments
///
/// * `shim` — The shim layer containing DLL name, target crate, and mappings.
/// * `mode` — Generation mode controlling stub completeness.
///
/// # Generated Code
///
/// The output includes:
/// - Module doc comments with provenance (source DLL, target crate, mapping count)
/// - Crate dependency imports derived from the target crate name
/// - A `ShimState` struct if any mapping requires shared resource tracking
/// - One `pub unsafe fn` per mapping, with parameter transforms documented
///   in inline comments
///
/// # Example
///
/// ```no_run
/// use calxgloss_types::ShimLayer;
/// use calxgloss_analysis::shim_gen::{generate_shim_source, ShimGenerationMode};
///
/// # let shim = ShimLayer::new("d3d9.dll".to_string(), "wgpu".to_string());
/// let source = generate_shim_source(&shim, ShimGenerationMode::Skeletal);
/// ```
pub fn generate_shim_source(shim: &ShimLayer, mode: ShimGenerationMode) -> String {
    let mut output = String::new();

    // Module-level doc comment.
    append_doc_header(&mut output, shim);

    // Blank line after doc comments.
    if !output.ends_with('\n') {
        output.push('\n');
    }
    output.push_str("\n");

    // Use declarations for the target crate.
    append_use_declarations(&mut output, shim);

    output.push('\n');

    // Module-level state (if needed).
    if needs_state(shim) {
        append_state_struct(&mut output, shim);
        output.push('\n');
    }

    // Exported shim functions.
    append_shim_functions(&mut output, shim, &mode);

    output
}

// ============================================================
// Doc header
// ============================================================

fn append_doc_header(output: &mut String, shim: &ShimLayer) {
    let comment = format!(
        "//! Auto-generated shim layer for `{src_dll}`.\n\
         //!\n\
         //! This module translates calls from the original `{src_dll}` API surface\n\
         //! into equivalent calls on the `{crate_name}` crate. It is generated by\n\
         //! the Calxgloss reverse engineering harness and should not be edited by hand.\n\
         //!\n\
         //! Every exported function from the original DLL is implemented here, routing\n\
         //! through the corresponding `{crate_name}` API.\n\
         //!\n\
         //! **Source:** `{src_dll}`\n\
         //! **Target crate:** `{crate_name}`\n\
         //! **Mappings:** {count}",
        src_dll = shim.source_dll,
        crate_name = shim.target_crate,
        count = shim.mapping_count(),
    );
    output.push_str(&comment);
    output.push('\n');
}

// ============================================================
// Use declarations
// ============================================================

/// Collects the set of crate root dependencies needed by the shim.
///
/// For known crates (wgpu, cpal, fmod-rs, vb6runtime), the crate root
/// is returned. For unknown crates, the crate root is `"{{ crate_name }}"`
/// as a placeholder.
fn collect_crate_deps(shim: &ShimLayer) -> Vec<String> {
    let crate_root = shim_crate_root(&shim.target_crate);
    if shim.mappings.is_empty() {
        return Vec::new();
    }
    vec![format!("use {crate_root};")]
}

fn shim_crate_root(crate_name: &str) -> String {
    // Known crates have their official crate name as the dependency.
    // Unknown crates are referenced by name (to be filled in during manual review).
    match crate_name {
        "wgpu" => "wgpu",
        "tiny-skia" => "tiny_skia",
        "cpal" => "cpal",
        "fmod-rs" => "fmod_rs",
        "vb6runtime" => "vb6runtime",
        _ => crate_name,
    }
    .to_string()
}

fn append_use_declarations(output: &mut String, shim: &ShimLayer) {
    let deps = collect_crate_deps(shim);
    if deps.is_empty() {
        return;
    }

    for dep in &deps {
        output.push_str(dep);
        output.push('\n');
    }
}

// ============================================================
// State struct
// ============================================================

/// Determines whether the shim layer requires shared state.
///
/// A shim needs state when any mapping requires resource tracking
/// (e.g., texture heaps, device contexts, sound buffers) that outlive
/// individual function calls.
fn needs_state(shim: &ShimLayer) -> bool {
    shim.mappings.iter().any(|m| {
        // Heuristic: if parameter transforms mention "heap", "track",
        // "lookup", "register", or "allocate", state is likely needed.
        let needs_tracking = ["heap", "track", "lookup", "register", "allocate", "context"]
            .iter()
            .any(|keyword| m.parameter_transforms.iter().any(|t| t.to_lowercase().contains(keyword)));

        // High complexity mappings that involve resource management need state.
        let high_complexity = matches!(m.complexity, ComplexityScore::High);

        // Non-identity return mappings that aren't simple conversions
        // may need state for managing the conversion.
        let needs_return_state = matches!(
            &m.return_mapping,
            ReturnMapping::Custom(_) | ReturnMapping::Converted(_)
        );

        needs_tracking || (high_complexity && needs_return_state)
    })
}

/// Extracts state field suggestions from mapping parameter transforms.
///
/// Scans parameter transforms for resource-tracking keywords and produces
/// suggested `ShimState` field definitions.
fn extract_state_fields(shim: &ShimLayer) -> Vec<StateField> {
    let mut fields: Vec<StateField> = Vec::new();
    let mut seen = std::collections::HashSet::new();

    for mapping in &shim.mappings {
        for transform in &mapping.parameter_transforms {
            let lower = transform.to_lowercase();

            if lower.contains("heap") && seen.insert("texture_heap") {
                fields.push(StateField {
                    name: "texture_heap".to_string(),
                    typ: "std::collections::HashMap<u32, wgpu::TextureView>".to_string(),
                    default: "Default::default()".to_string(),
                    comment: "Maps original texture handles to wgpu TextureViews".to_string(),
                });
            }

            if lower.contains("track") && seen.insert("tracked_resources") {
                fields.push(StateField {
                    name: "tracked_resources".to_string(),
                    typ: "std::collections::HashMap<u32, ResourceType>".to_string(),
                    default: "Default::default()".to_string(),
                    comment: "Tracks resource lifetimes for the original DLL".to_string(),
                });
            }

            if lower.contains("device") && lower.contains("context") && seen.insert("device_context") {
                fields.push(StateField {
                    name: "device_context".to_string(),
                    typ: "Option<wgpu::Device>".to_string(),
                    default: "None".to_string(),
                    comment: "Cached wgpu device for the shim layer".to_string(),
                });
            }
        }
    }

    fields
}

/// A suggested field for the shim's shared state struct.
struct StateField {
    name: String,
    typ: String,
    default: String,
    comment: String,
}

fn append_state_struct(output: &mut String, shim: &ShimLayer) {
    let fields = extract_state_fields(shim);
    if fields.is_empty() {
        return;
    }

    // Write the ShimState struct.
    output.push_str("/// Shared state managed by this shim layer.\n\
                     ///\n\
                     /// Tracks cross-cutting resources that outlive individual\n\
                     /// function calls.\n");
    output.push_str("pub struct ShimState {\n");
    for field in &fields {
        output.push_str(&format!("    /// {}\n", field.comment));
        output.push_str(&format!("    pub {}: {},\n", field.name, field.typ));
    }
    output.push_str("}\n\n");

    // Write the impl block.
    output.push_str("impl ShimState {\n");
    output.push_str("    /// Creates a new, empty shim state.\n");
    output.push_str("    pub fn new() -> Self {\n");
    output.push_str("        Self {\n");
    for field in &fields {
        output.push_str(&format!("            {}: {},\n", field.name, field.default));
    }
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("impl Default for ShimState {\n");
    output.push_str("    fn default() -> Self {\n");
    output.push_str("        Self::new()\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    // Static instance and accessor.
    output.push_str("static mut SHIM_STATE: ShimState = ShimState::new();\n\n");
    output.push_str(
        "/// Returns a mutable reference to the shim's shared state.\n\
         ///\n\
         /// # Safety\n\
         ///\n\
         /// Callers must ensure that access to the state is properly synchronized.\n",
    );
    output.push_str("pub unsafe fn shim_state() -> &'static mut ShimState {\n");
    output.push_str("    &mut SHIM_STATE\n");
    output.push_str("}\n");
}

// ============================================================
// Shim function bodies
// ============================================================

fn append_shim_functions(
    output: &mut String,
    shim: &ShimLayer,
    mode: &ShimGenerationMode,
) {
    let has_state = needs_state(shim);
    for mapping in &shim.mappings {
        append_shim_function(output, mapping, has_state, mode);
        output.push('\n');
    }
}

fn append_shim_function(
    output: &mut String,
    mapping: &ShimApiMapping,
    has_state: bool,
    mode: &ShimGenerationMode,
) {
    let fn_name = rust_fn_name(&mapping.original_api);

    // Doc comment.
    let mut doc = format!(
        "/// Shim for `{original_api}`.\n\
         ///\n\
         /// Maps `{original_api}({params})`\n\
         /// -> `{crate_api}`.",
        original_api = mapping.original_api,
        params = mapping
            .original_params
            .iter()
            .map(|p| p.as_str())
            .collect::<Vec<_>>()
            .join(", "),
        crate_api = mapping.crate_api,
    );

    if !mapping.notes.is_empty() {
        doc.push_str("\n///\n/// **Note:** ");
        doc.push_str(&mapping.notes);
        doc.push(']');
    }

    output.push_str(&doc);

    // Function signature.
    let shim_params = format_shim_params(&mapping.original_params);
    let ret = shim_return_type(&mapping.return_mapping);

    output.push_str(&format!(
        "pub unsafe fn {fn_name}({params}) {ret} {{\n",
        fn_name = fn_name,
        params = shim_params,
    ));

    // Access state if needed.
    if has_state {
        output.push_str("        let state = unsafe { shim_state() };\n");
    }

    // Parameter transform comments.
    for transform in &mapping.parameter_transforms {
        output.push_str(&format!("        // Transform: {transform}\n"));
    }

    // Function body.
    match mode {
        ShimGenerationMode::Complete => {
            append_complete_body(output, mapping);
        }
        ShimGenerationMode::Skeletal => {
            append_skeletal_body(output, mapping);
        }
    }

    output.push_str("    }\n");
}

/// Converts a Windows DLL function name to a Rust function name.
///
/// Applies snake_case conversion:
/// - Insert underscore before uppercase letters that follow lowercase letters
///   (e.g., "SetTexture" -> "set_texture").
/// - Collapse consecutive uppercase letters as an acronym (e.g., "Direct3D"
///   -> "direct3d", "IDirect3D" -> "idirect3d").
/// - Convert to lowercase.
///
/// # Examples
///
/// ```
/// use calxgloss_analysis::shim_gen::rust_fn_name;
///
/// assert_eq!(rust_fn_name("SetTexture"), "set_texture");
/// assert_eq!(rust_fn_name("Direct3DCreate9"), "direct3dcreate9");
/// assert_eq!(rust_fn_name("CreateFileA"), "create_file_a");
/// assert_eq!(rust_fn_name("BitBlt"), "bit_blt");
/// ```
pub fn rust_fn_name(name: &str) -> String {
    let mut result = String::with_capacity(name.len() + 4);
    let chars: Vec<char> = name.chars().collect();
    let len = chars.len();

    for i in 0..len {
        let c = chars[i];
        if c.is_uppercase() {
            // Insert underscore before uppercase if preceded by a lowercase
            // letter (e.g., "SetTexture" -> "Set_Texture").
            // Do NOT insert for consecutive uppercase letters (e.g., "Direct3D"
            // -> "direct3d", "IDirect3D" -> "idirect3d").
            if i > 0 && chars[i - 1].is_lowercase() {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap_or(c));
        } else {
            result.push(c);
        }
    }

    result
}

fn format_shim_params(params: &[String]) -> String {
    if params.is_empty() {
        return String::new();
    }

    // Convert Windows API parameter types to FFI-compatible Rust types.
    params
        .iter()
        .map(|p| convert_param_to_rust(p))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Converts a Windows API parameter declaration to a Rust FFI-compatible type.
///
/// Handles common Windows types:
/// - `UINT`, `ULONG`, `DWORD`, `UCHAR`, `BYTE` → `u32` or `u8`
/// - `INT`, `LONG`, `LPARAM`, `WPARAM` → `i32` or `i64`
/// - `LPVOID`, `PVOID`, `*const c_void`, `HANDLE` → `*const c_void`
/// - `LPCWSTR`, `LPCSTR`, `LPCTSTR`, `*const c_char` → `*const c_char`
/// - `BOOL` → `i32` (Windows BOOL is 32-bit)
/// - `HRESULT` → `i32`
/// - `IDirect3D*9*`, `**` pointer types → `*mut c_void`
fn convert_param_to_rust(param: &str) -> String {
    let trimmed = param.trim();
    if trimmed.is_empty() {
        return "c_void".to_string();
    }

    // Split into type and optional name.
    let parts: Vec<&str> = trimmed.split_whitespace().collect();
    let type_part = parts[0];
    let name_part = parts.get(1).copied().unwrap_or("param");

    // Determine the Rust type.
    let rust_type = match type_part {
        // Unsigned integers.
        "UINT" | "ULONG" | "DWORD" | "BOOL" | "WPARAM" => "u32",
        "UCHAR" | "BYTE" | "BOOLEAN" => "u8",
        "USHORT" | "WORD" => "u16",
        "ULONGLONG" | "DWORDLONG" => "u64",
        // Signed integers.
        "INT" | "LONG" | "LPARAM" | "HRESULT" | "LRESULT" => "i32",
        "LONGLONG" | "LONG64" => "i64",
        // Pointers and handles.
        "LPVOID" | "PVOID" | "HANDLE" | "HMODULE" | "HINSTANCE" | "HDC" | "HWND"
        | "HDWP" | "HRGN" | "HBITMAP" | "HPALETTE" | "HGLRC" | "HCURSOR"
        | "HMENU" | "HFONT" | "HBRUSH" => "*mut core::ffi::c_void",
        // Const pointers / strings.
        "LPCVOID" | "LPCSTR" | "LPCWSTR" | "LPCTSTR" | "LPCOLESTR" => "*const core::ffi::c_char",
        "LPTSTR" | "LPTCH" | "LPSTR" | "LPOLESTR" => "*mut core::ffi::c_char",
        // COM interface pointers (double pointer = output parameter).
        _ if type_part.ends_with("***") => "*mut *mut core::ffi::c_void",
        _ if type_part.ends_with("**") => "*mut *mut core::ffi::c_void",
        _ if type_part.ends_with("*") => "*mut core::ffi::c_void",
        // fmod types.
        "FMOD_SOUND" | "FMOD_CHANNEL" | "FMOD_CHANNELGROUP" | "FMOD_DSP" | "FMOD_STUDIO_SYSTEM"
        | "FMOD_MODE" | "FMOD_CHANNELCONTROL_TYPE" => "*mut core::ffi::c_void",
        "FMOD_RESULT" => "i32",
        "FMOD_VECTOR" => "*const FMOD_VECTOR",
        // cpal types.
        "SAMPLE_RATE" | "FORMAT" => "u32",
        // Default: treat as pointer.
        _ => "*mut core::ffi::c_void",
    };

    format!("{name_part}: {rust_type}")
}

fn shim_return_type(return_mapping: &ReturnMapping) -> String {
    match return_mapping {
        ReturnMapping::Identity | ReturnMapping::Converted(_) => " -> i32".to_string(),
        ReturnMapping::Void | ReturnMapping::Discarded => " -> ()".to_string(),
        ReturnMapping::Custom(_) => " -> *mut core::ffi::c_void".to_string(),
    }
}

fn append_complete_body(output: &mut String, mapping: &ShimApiMapping) {
    let target_api = escape_crate_path(&mapping.crate_api);
    let crate_root = shim_crate_root(&mapping.crate_api.split("::").next().unwrap_or(""));
    let call_args = convert_call_args(&mapping.crate_params, &mapping.original_params);

    match &mapping.return_mapping {
        ReturnMapping::Void | ReturnMapping::Discarded => {
            output.push_str(&format!(
                "        {crate_root}::{target_api}({args});\n",
                crate_root = crate_root,
                target_api = target_api,
                args = call_args,
            ));
        }
        ReturnMapping::Identity => {
            output.push_str(&format!(
                "        let _result = {crate_root}::{target_api}({args});\n",
                crate_root = crate_root,
                target_api = target_api,
                args = call_args,
            ));
        }
        ReturnMapping::Converted(desc) => {
            output.push_str(&format!(
                "        // Convert return value: {desc}\n",
                desc = desc,
            ));
            output.push_str(&format!(
                "        let _result = {crate_root}::{target_api}({args});\n",
                crate_root = crate_root,
                target_api = target_api,
                args = call_args,
            ));
        }
        ReturnMapping::Custom(desc) => {
            output.push_str(&format!(
                "        // TODO: custom return conversion — {desc}\n",
                desc = desc,
            ));
            output.push_str(&format!(
                "        let _result = {crate_root}::{target_api}({args});\n",
                crate_root = crate_root,
                target_api = target_api,
                args = call_args,
            ));
        }
    }
}

fn append_skeletal_body(output: &mut String, mapping: &ShimApiMapping) {
    let note = if mapping.parameter_transforms.is_empty() {
        "no parameter transforms needed".to_string()
    } else {
        format!(
            "{} transform(s) needed",
            mapping.parameter_transforms.len()
        )
    };

    let return_note = match &mapping.return_mapping {
        ReturnMapping::Identity | ReturnMapping::Converted(_) | ReturnMapping::Custom(_) => {
            format!(" return value: {:?}", mapping.return_mapping)
        }
        ReturnMapping::Void | ReturnMapping::Discarded => String::new(),
    };

    output.push_str(&format!(
        "        // TODO: implement `{original_api}` -> `{crate_api}`\n\
         //       ({note}{ret_note})\n\
         //       Parameters: {params}\n",
        original_api = mapping.original_api,
        crate_api = mapping.crate_api,
        note = note,
        ret_note = return_note,
        params = mapping
            .original_params
            .iter()
            .map(|p| p.as_str())
            .collect::<Vec<_>>()
            .join(", "),
    ));
}

/// Converts crate API parameter positions to call argument expressions.
///
/// Takes the crate API parameter list and the original parameter list,
/// and produces argument expressions suitable for a function call.
fn convert_call_args(crate_params: &[String], _original_params: &[String]) -> String {
    if crate_params.is_empty() {
        return String::new();
    }

    // Map each crate parameter to a Rust expression.
    crate_params
        .iter()
        .map(|cp| {
            // Extract the variable name (before the colon or the full type if no colon).
            let name = cp
                .split_once(':')
                .map(|(n, _)| n.trim())
                .unwrap_or(cp.trim());

            // If the name looks like a type (no variable), derive from position.
            if is_type_only(name) {
                format!("arg_{}", name)
            } else {
                name.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Returns `true` if the given name looks like a type annotation
/// rather than a variable name.
fn is_type_only(name: &str) -> bool {
    // If it contains `::`, `&`, `<`, or matches known type names,
    // it's likely a type rather than a variable.
    name.contains("::")
        || name.contains('&')
        || name.contains('<')
        || matches!(
            name,
            "u32" | "u64" | "i32" | "i64" | "f32" | "f64"
                | "usize" | "isize" | "bool" | "char"
                | "str" | "String" | "&str" | "&String"
        )
}

/// Escapes a crate API path for use in generated code.
fn escape_crate_path(path: &str) -> String {
    path.to_string()
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_shim() -> ShimLayer {
        let mut shim = ShimLayer::new("d3d9.dll".to_string(), "wgpu".to_string());
        shim.add_mapping(ShimApiMapping {
            original_api: "Direct3DCreate9".to_string(),
            original_params: vec!["UINT Ordinal".to_string()],
            crate_api: "wgpu::Instance::new".to_string(),
            crate_params: vec!["wgpu::Backends".to_string()],
            parameter_transforms: vec![
                "Ordinal -> map to wgpu::Backends::VULKAN | BACKENDS".to_string(),
            ],
            return_mapping: ReturnMapping::Converted(
                "Returns interface pointer -> convert to wgpu::Instance".to_string(),
            ),
            complexity: ComplexityScore::High,
            notes: "DX9 creates a single global D3D object; wgpu uses Instance per process."
                .to_string(),
        });
        shim.add_mapping(ShimApiMapping {
            original_api: "Present".to_string(),
            original_params: vec![],
            crate_api: "wgpu::Queue::submit".to_string(),
            crate_params: vec!["&[&wgpu::CommandBuffer]".to_string()],
            parameter_transforms: vec!["no params".to_string()],
            return_mapping: ReturnMapping::Void,
            complexity: ComplexityScore::Medium,
            notes: String::new(),
        });
        shim
    }

    #[test]
    fn test_generate_skeletal_shim() {
        let shim = sample_shim();
        let source = generate_shim_source(&shim, ShimGenerationMode::Skeletal);

        // Check that the module doc comment is present.
        assert!(source.contains("d3d9.dll"));
        assert!(source.contains("wgpu"));
        assert!(source.contains("Mappings:** 2"));

        // Check that shim functions are generated (snake_case).
        assert!(source.contains("unsafe fn direct3dcreate9"));
        assert!(source.contains("unsafe fn present"));

        // Check that TODO stubs are present.
        assert!(source.contains("TODO"));

        // Check that parameter transforms appear as comments.
        assert!(source.contains("Transform: Ordinal -> map to wgpu::Backends"));
    }

    #[test]
    fn test_generate_complete_shim() {
        let shim = sample_shim();
        let source = generate_shim_source(&shim, ShimGenerationMode::Complete);

        // Complete mode should produce actual function calls.
        assert!(source.contains("wgpu::Instance::new"));
        assert!(source.contains("wgpu::Queue::submit"));

        // Should not have TODO for known mappings.
        assert!(!source.contains("TODO"));
    }

    #[test]
    fn test_shim_needs_state_for_high_complexity_with_custom_return() {
        let mut shim = ShimLayer::new("test.dll".to_string(), "wgpu".to_string());
        shim.add_mapping(ShimApiMapping {
            original_api: "SomeFunc".to_string(),
            original_params: vec!["UINT".to_string()],
            crate_api: "wgpu::some_func".to_string(),
            crate_params: vec!["u32".to_string()],
            parameter_transforms: vec!["direct cast".to_string()],
            return_mapping: ReturnMapping::Custom("complex conversion".to_string()),
            complexity: ComplexityScore::High,
            notes: String::new(),
        });
        assert!(needs_state(&shim));
    }

    #[test]
    fn test_shim_no_state_for_simple_mappings() {
        let mut shim = ShimLayer::new("test.dll".to_string(), "wgpu".to_string());
        shim.add_mapping(ShimApiMapping {
            original_api: "SimpleFunc".to_string(),
            original_params: vec!["u32".to_string()],
            crate_api: "wgpu::simple_func".to_string(),
            crate_params: vec!["u32".to_string()],
            parameter_transforms: vec!["direct pass-through".to_string()],
            return_mapping: ReturnMapping::Identity,
            complexity: ComplexityScore::Low,
            notes: String::new(),
        });
        assert!(!needs_state(&shim));
    }

    #[test]
    fn test_convert_param_to_rust_windows_types() {
        assert_eq!(convert_param_to_rust("UINT x"), "x: u32");
        assert_eq!(convert_param_to_rust("LPVOID ptr"), "ptr: *mut core::ffi::c_void");
        assert_eq!(convert_param_to_rust("LPCSTR name"), "name: *const core::ffi::c_char");
        assert_eq!(convert_param_to_rust("HWND hwnd"), "hwnd: *mut core::ffi::c_void");
        assert_eq!(convert_param_to_rust("HRESULT hr"), "hr: i32");
        assert_eq!(convert_param_to_rust("BOOL f"), "f: u32");
        assert_eq!(convert_param_to_rust("IDirect3D9*** pp"), "pp: *mut *mut core::ffi::c_void");
        assert_eq!(convert_param_to_rust("void"), "param: *mut core::ffi::c_void");
    }

    #[test]
    fn test_convert_param_to_rust_empty_param() {
        assert_eq!(convert_param_to_rust(""), "c_void");
    }

    #[test]
    fn test_empty_shim_produces_valid_module() {
        let shim = ShimLayer::new("empty.dll".to_string(), "empty-crate".to_string());
        let source = generate_shim_source(&shim, ShimGenerationMode::Skeletal);

        assert!(source.contains("empty.dll"));
        assert!(source.contains("empty-crate"));
        assert!(source.contains("Mappings:** 0"));
        // No functions should be generated for empty mappings.
        assert!(!source.contains("unsafe fn "));
    }

    #[test]
    fn test_module_name_conversion() {
        use calxgloss_types::dll_to_module_name;

        assert_eq!(dll_to_module_name("d3d9.dll"), "d3d9");
        assert_eq!(dll_to_module_name("fmod.dll"), "fmod");
        assert_eq!(dll_to_module_name("my_lib.dll"), "my_lib");
        assert_eq!(dll_to_module_name("kernel32"), "kernel32");
        assert_eq!(dll_to_module_name("WINGUI.DLL"), "wingui");
    }

    #[test]
    fn test_generated_code_structure() {
        let mut shim = ShimLayer::new("test.dll".to_string(), "wgpu".to_string());
        shim.add_mapping(ShimApiMapping {
            original_api: "TestFunc".to_string(),
            original_params: vec!["UINT a".to_string(), "LPVOID b".to_string()],
            crate_api: "wgpu::test_func".to_string(),
            crate_params: vec!["u32".to_string()],
            parameter_transforms: vec!["a -> direct cast".to_string()],
            return_mapping: ReturnMapping::Void,
            complexity: ComplexityScore::Low,
            notes: "Test mapping".to_string(),
        });

        let source = generate_shim_source(&shim, ShimGenerationMode::Complete);

        // Check structure: doc -> use -> functions.
        assert!(source.starts_with("//!"));
        assert!(source.contains("use "));
        assert!(source.contains("unsafe fn test_func"));
        assert!(source.contains("wgpu::test_func"));
        assert!(source.contains("Transform: a -> direct cast"));
    }

    #[test]
    fn test_rust_fn_name_generation() {
        assert_eq!(rust_fn_name("SetTexture"), "set_texture");
        assert_eq!(rust_fn_name("Direct3DCreate9"), "direct3dcreate9");
        assert_eq!(rust_fn_name("CreateFileA"), "create_file_a");
        assert_eq!(rust_fn_name("BitBlt"), "bit_blt");
    }

    #[test]
    fn test_shim_crate_root_mapping() {
        assert_eq!(shim_crate_root("wgpu"), "wgpu");
        assert_eq!(shim_crate_root("tiny-skia"), "tiny_skia");
        assert_eq!(shim_crate_root("cpal"), "cpal");
        assert_eq!(shim_crate_root("fmod-rs"), "fmod_rs");
        assert_eq!(shim_crate_root("vb6runtime"), "vb6runtime");
        assert_eq!(shim_crate_root("unknown-crate"), "unknown-crate");
    }
}
