[package]
name = "calxgloss-analysis"
version.workspace = true
edition.workspace = true
description = "DLL classification, call graph analysis, and Windows API tagging"
license.workspace = true
repository.workspace = true

[dev-dependencies]
chrono = { workspace = true }

[dependencies]
calxgloss-types = { path = "../calxgloss-types" }
calxgloss-ghidra = { path = "../calxgloss-ghidra" }
calxgloss-pal = { path = "../calxgloss-pal" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
