//! Harness source generation.

use anyhow::Result;

use crate::wine::types::HarnessSpec;

use std::fmt::Write as _;

/// Generate the generated harness's `invoke` function.
///
/// This is the only part that varies per function, so it is generated between
/// two fixed chunks of harness code.
pub fn generate_invoke(spec: &HarnessSpec) -> Result<String> {
    let expected = spec.params.len();
    let mut out = String::new();

    // Buffers requested by pointer arguments must outlive the call into the target
    // function, so they are held in an arena. Only emitted when a pointer is
    // actually present, otherwise it would be an unused binding.
    let has_pointer = spec
        .params
        .iter()
        .any(|p| p.kind == crate::wine::ScalarKind::Ptr);

    writeln!(
        out,
        "/// Call the function under test with the arguments supplied on the wire.\n\
         \x20   if fields.len() != {expected} {{\n\
         \x20       return Err(format!(\"expected {expected} arguments, got {{}}\", fields.len()));\n\
         \x20   }}"
    )
    .expect("writing to a String cannot fail");

    if has_pointer {
        writeln!(
            out,
            "    // Buffers requested by pointer arguments must outlive the call, so they\n\
             \x20   // are held here rather than in the argument bindings.\n\
             \x20   let mut arena: Vec<Vec<u8>> = Vec::new();"
        )
        .expect("writing to a String cannot fail");
    }

    for (i, p) in spec.params.iter().enumerate() {
        let tag = p.kind.tag();
        let parse = match p.kind {
            crate::wine::ScalarKind::I8 => "as_i8",
            crate::wine::ScalarKind::I16 => "as_i16",
            crate::wine::ScalarKind::I32 => "as_i32",
            crate::wine::ScalarKind::I64 => "as_i64",
            crate::wine::ScalarKind::U8 => "as_u8",
            crate::wine::ScalarKind::U16 => "as_u16",
            crate::wine::ScalarKind::U32 => "as_u32",
            crate::wine::ScalarKind::U64 => "as_u64",
            crate::wine::ScalarKind::F32 => "as_f32",
            crate::wine::ScalarKind::F64 => "as_f64",
            crate::wine::ScalarKind::Unit => "as_void",
            // A pointer may name an address or request an allocation; either way
            // it is reinterpreted as the declared pointer type, so `*mut i8` and
            // `*const u16` both work.
            crate::wine::ScalarKind::Ptr => {
                writeln!(
                    out,
                    "    let a{i} = ptr_arg(fields[{i}], \"{tag}\", &mut arena)? as {ty};",
                    ty = p.rust_type
                )
                .expect("writing to a String cannot fail");
                continue;
            }
        };
        writeln!(
            out,
            "    let a{i} = {parse}(field(fields[{i}], \"{tag}\")?)?;"
        )
        .expect("writing to a String cannot fail");
    }

    let arg_list = (0..expected)
        .map(|i| format!("a{i}"))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(
        out,
        "    type TargetFn = {};\n\
         \x20   let func: TargetFn = unsafe {{ std::mem::transmute(addr) }};",
        spec.fn_pointer_type()
    )
    .expect("writing to a String cannot fail");

    match spec.return_kind {
        crate::wine::ScalarKind::Unit => {
            writeln!(out, "    func({arg_list});").expect("writing to a String cannot fail");
            writeln!(out, "    Ok(String::new())").expect("writing to a String cannot fail");
        }
        kind => {
            writeln!(out, "    let r = func({arg_list});")
                .expect("writing to a String cannot fail");
            let rendered = match kind {
                crate::wine::ScalarKind::F32 => "format!(\"f32:0x{:08x}\", r.to_bits())".to_string(),
                crate::wine::ScalarKind::F64 => "format!(\"f64:0x{:016x}\", r.to_bits())".to_string(),
                crate::wine::ScalarKind::Ptr => {
                    "if r.is_null() { \"p:null\".to_string() } else { format!(\"p:0x{:x}\", r as usize) }"
                        .to_string()
                }
                // Integers go out in decimal. `{r}` captures the binding, so no
                // positional argument is passed.
                _ => format!("format!(\"{}:{{r}}\")", kind.tag()),
            };
            writeln!(out, "    Ok({rendered})").expect("writing to a String cannot fail");
        }
    }

    writeln!(out, "}}\n").expect("writing to a String cannot fail");
    Ok(out)
}

/// Fixed harness code that precedes the generated `invoke`.
const HARNESS_PREFIX: &str = r##"// Auto-generated by calxgloss-testgen. Do not edit.
//
// Loads a Windows DLL, resolves one function inside it, and calls it once per
// input line. Test cases arrive on stdin; one result line is written to stdout
// per case. This crate intentionally has no dependencies so that cross-compiling
// it stays hermetic and fast.
use std::ffi::c_void;

type Hmodule = *mut c_void;

/// Maps the image without running DllMain and without resolving imports.
const DONT_RESOLVE_DLL_REFERENCES: u32 = 0x0000_0001;

/// Largest buffer to allocate for one test case.
///
/// Mirrors the host-side limit; allocation size arrives as test data, so it needs
/// a bound here as well.
const MAX_ALLOC: usize = 256 * 1024 * 1024;

/// Field separator between arguments on stdin.
const US: char = '\u{1f}';

/// Exit status the harness uses when the function under test faulted.
const CRASH_EXIT: u32 = __CRASH_EXIT__;

#[link(name = "kernel32")]
extern "system" {
    fn LoadLibraryExW(name: *const u16, file: Hmodule, flags: u32) -> Hmodule;
    fn GetLastError() -> u32;
    fn GetProcAddress(module: Hmodule, name: *const u8) -> *mut c_void;
    fn SetUnhandledExceptionFilter(f: Option<CrashHandler>) -> u64;
    fn TerminateProcess(handle: *mut c_void, code: u32) -> u32;
    fn GetCurrentProcess() -> *mut c_void;
}

type CrashHandler = extern "system" fn(code: u32) -> u8;

/// Terminate the process the moment a fault escapes the call under test.
///
/// Without this, Windows escalates the exception to `winedbg`, which pops up an
/// interactive crash dialog and writes a register dump to *stdout* — the same
/// stream the results travel on. Terminating here keeps a faulting test case
/// cheap, headless, and unable to corrupt the results already emitted.
extern "system" fn on_crash(_code: u32) -> u8 {
    unsafe {
        let _ = TerminateProcess(GetCurrentProcess(), CRASH_EXIT);
    }
    // Unreachable in practice; returning non-zero would resume the search.
    1
}

/// Abort with a message on stderr. Exit codes are distinct per failure mode so
/// the caller can tell a bad invocation from a bad DLL.
fn die(code: i32, msg: &str) -> ! {
    eprintln!("harness: {msg}");
    std::process::exit(code)
}

fn parse_hex(s: &str) -> Result<u64, String> {
    let t = s.trim();
    let t = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")).unwrap_or(t);
    u64::from_str_radix(t, 16).map_err(|e| format!("'{t}' is not a hex value: {e}"))
}

/// Split a `<tag>:<value>` field, checking the tag is the one expected.
///
/// Validating the tag means a mismatch between the caller's marshalling and the
/// generated signature is reported as such, rather than surfacing as a confusing
/// parse failure on the value.
fn field<'a>(raw: &'a str, expect: &str) -> Result<&'a str, String> {
    match raw.split_once(':') {
        Some((tag, value)) if tag == expect => Ok(value),
        Some((tag, _)) => Err(format!("expected a '{expect}' field, got a '{tag}' field")),
        None => Err(format!("field '{raw}' is missing its '{expect}:' tag")),
    }
}

fn as_i8(s: &str) -> Result<i8, String> { s.trim().parse().map_err(|e| format!("i8: {e}")) }
fn as_i16(s: &str) -> Result<i16, String> { s.trim().parse().map_err(|e| format!("i16: {e}")) }
fn as_i32(s: &str) -> Result<i32, String> { s.trim().parse().map_err(|e| format!("i32: {e}")) }
fn as_i64(s: &str) -> Result<i64, String> { s.trim().parse().map_err(|e| format!("i64: {e}")) }
fn as_u8(s: &str) -> Result<u8, String> { s.trim().parse().map_err(|e| format!("u8: {e}")) }
fn as_u16(s: &str) -> Result<u16, String> { s.trim().parse().map_err(|e| format!("u16: {e}")) }
fn as_u32(s: &str) -> Result<u32, String> { s.trim().parse().map_err(|e| format!("u32: {e}")) }
fn as_u64(s: &str) -> Result<u64, String> { s.trim().parse().map_err(|e| format!("u64: {e}")) }
fn as_f32(s: &str) -> Result<f32, String> { parse_hex(s).map(|b| f32::from_bits(b as u32)) }
fn as_f64(s: &str) -> Result<f64, String> { parse_hex(s).map(f64::from_bits) }
fn as_void(_s: &str) -> Result<(), String> { Err("void value supplied as an argument".into()) }

/// Decode a pointer argument, allocating a buffer when the field asks for one.
///
/// Accepted forms:
/// - `null` — a null pointer
/// - `<addr>` — that address, in decimal or `0x`-prefixed hex
/// - `@<size>` — a freshly allocated zeroed buffer of `size` bytes
/// - `@<size>,<fill>` — a buffer of `size` bytes, every byte set to `fill`
///
/// Buffers are pushed onto `arena` so they outlive the call into the target
/// function. Each `Vec` owns its own heap allocation, so pushing more entries
/// never moves an already-handed-out pointer.
fn ptr_arg(raw: &str, expect: &str, arena: &mut Vec<Vec<u8>>) -> Result<*mut u8, String> {
    let value = field(raw, expect)?;
    let value = value.trim();
    if value.eq_ignore_ascii_case("null") {
        return Ok(std::ptr::null_mut());
    }

    if let Some(spec) = value.strip_prefix('@') {
        let (size_text, fill_text) = spec.split_once(',').unwrap_or((spec, ""));
        let size: usize = size_text
            .trim()
            .parse()
            .map_err(|e| format!("allocation size: {e}"))?;
        if size > MAX_ALLOC {
            return Err(format!(
                "refusing to allocate {size} bytes; the limit is {}",
                MAX_ALLOC
            ));
        }
        let fill: u8 = if fill_text.trim().is_empty() {
            0
        } else {
            parse_hex(fill_text).map(|b| b as u8).map_err(|e| format!("allocation fill: {e}"))?
        };
        arena.push(vec![fill; size]);
        return Ok(arena.last_mut().expect("just pushed").as_mut_ptr());
    }

    if value.starts_with("0x") || value.starts_with("0X") {
        return parse_hex(value).map(|a| a as usize as *mut u8);
    }
    value
        .parse::<i64>()
        .map(|a| a as usize as *mut u8)
        .map_err(|e| format!("pointer: {e}"))
}

/// Keep a message on a single line so the result framing stays intact.
fn clean(s: &str) -> String {
    s.replace(['\t', '\n', '\r'], " ")
}

"##;

/// Fixed harness code that follows the generated `invoke`.
const HARNESS_SUFFIX: &str = r##"
fn wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

fn main() {
    // Installed before anything else so it also covers a fault raised by the
    // loader while mapping the DLL.
    unsafe {
        SetUnhandledExceptionFilter(Some(on_crash));
    }
    let argv: Vec<String> = std::env::args().skip(1).collect();
    let mut binary = String::new();
    let mut locator: Option<(u8, String)> = None;
    let mut flags = DONT_RESOLVE_DLL_REFERENCES;
    // When set, run only this case index. Used to survive a crash in batch mode.
    let mut isolate: Option<usize> = None;

    let mut i = 0;
    while i < argv.len() {
        let arg = argv[i].clone();
        let value = argv.get(i + 1).cloned().unwrap_or_default();
        // How many argv slots this flag occupies, so the loop advances correctly.
        let consumed = match arg.as_str() {
            "--binary" => { binary = value; 1 }
            "--rva" => { locator = Some((0, value)); 1 }
            "--export-name" => { locator = Some((1, value)); 1 }
            "--export-ordinal" => { locator = Some((2, value)); 1 }
            "--run-binary-main" => { flags = 0; 0 }
            "--isolate" => { isolate = value.parse().ok(); 1 }
            other => {
                eprintln!("harness: ignoring unknown argument '{other}'");
                0
            }
        };
        i += 1 + consumed;
    }

    if binary.is_empty() {
        die(2, "--binary is required");
    }
    let Some((kind, value)) = locator else {
        die(2, "one of --rva, --export-name, or --export-ordinal is required");
    };

    let base = unsafe { LoadLibraryExW(wide(&binary).as_ptr(), std::ptr::null_mut(), flags) };
    if base.is_null() {
        let e = unsafe { GetLastError() };
        die(3, &format!("LoadLibraryExW failed: GetLastError={e} (0x{e:x})"));
    }
    let base_addr = base as usize;
    eprintln!("harness: module base = 0x{base_addr:016x}");

    // The base must be the start of a mapped image, not some other allocation.
    let mz = unsafe { std::ptr::read_unaligned(base_addr as *const u16) };
    if mz != 0x5a4d {
        die(4, &format!("base 0x{base_addr:x} lacks an MZ header (read 0x{mz:04x})"));
    }

    let addr = match kind {
        0 => match parse_hex(&value) {
            Ok(rva) => base_addr + rva as usize,
            Err(e) => die(2, &e),
        },
        1 => {
            let p = unsafe { GetProcAddress(base, value.as_ptr()) };
            if p.is_null() {
                die(5, &format!("export '{value}' not found"));
            }
            p as usize
        }
        _ => {
            let Ok(ord) = value.parse::<u16>() else {
                die(2, &format!("export ordinal '{value}' is not a number"));
            };
            let p = unsafe { GetProcAddress(base, ord as usize as *const u8) };
            if p.is_null() {
                die(5, &format!("export ordinal {ord} not found"));
            }
            p as usize
        }
    };
    eprintln!("harness: function address = 0x{addr:016x}");

    let mut input = String::new();
    if std::io::Read::read_to_string(&mut std::io::stdin(), &mut input).is_err() {
        die(6, "could not read test cases from stdin");
    }

    use std::io::Write as _;
    // Each result is emitted as it is produced rather than accumulated, because a
    // function that faults takes the process down and would otherwise discard
    // every result computed before it.
    let mut out = std::io::stdout();
    for (offset, line) in input.lines().enumerate() {
        // In isolation mode stdin carries exactly the one requested case, so the
        // first line is that case and must be labelled with the requested index.
        let index = match isolate {
            Some(requested) => requested + offset,
            None => offset,
        };
        let fields: Vec<&str> = line.split(US).filter(|f| !f.trim().is_empty()).collect();
        let result = match invoke(addr, &fields) {
            Ok(value) => format!("{index}\tok\t{}", clean(&value)),
            Err(message) => format!("{index}\terr\t{}", clean(&message)),
        };
        if writeln!(out, "{result}").is_err() || out.flush().is_err() {
            // The reader has gone away; nothing useful is left to do.
            die(7, "could not write results to stdout");
        }
    }
}
"##;

/// Exit status a generated harness uses when the function under test faulted.
///
/// Substituted into the harness source in place of `__CRASH_EXIT__`, so the
/// runner and the harness it launches cannot drift apart.
pub const HARNESS_CRASH_EXIT: u32 = 133;

/// Generate the complete harness source for a spec.
pub fn generate_harness(spec: &HarnessSpec) -> Result<String> {
    let mut src = String::with_capacity(8 * 1024);
    src.push_str(&HARNESS_PREFIX.replace("__CRASH_EXIT__", &HARNESS_CRASH_EXIT.to_string()));
    src.push_str(&generate_invoke(spec)?);
    src.push_str(HARNESS_SUFFIX);
    Ok(src)
}
